; ============================================================
; 1. 变量定义区 (确保所有子环境引用的变量名一致)
; ============================================================
[common]
lib_deps_base = 
    littlefs
    bblanchon/ArduinoJson@^6.21.4
    esphome/ESP32-audioI2S@^2.0.7
    knolleary/PubSubClient
    h2zero/NimBLE-Arduino
    gilmaimon/ArduinoWebsockets@^0.5.3
    plageoj/UrlEncode@^1.0.1

; 默认排除所有特殊功能文件夹，只保留基础功能
filter_base = +<*> -<dev_*> -<ai/> -<tftv/> -<tftd/>

; ============================================================
; 2. 全局基础设置
; ============================================================
[env]
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 460800


[env:esp32s3_n16r8]
platform = espressif32@6.5.0 ;//必须指定版本，否则最新版本会报错屏幕不停重启。
board = esp32-s3-devkitc-1
board_build.partitions = esp32s3_16MB.csv
board_build.arduino.memory_type = qio_opi ;确保 board_build.arduino.memory_type = qio_opi，否则摄像头驱动在申请分配大尺寸缓冲区时会失败。
board_upload.flash_size = 16MB
upload_speed = 460800
board_build.filesystem = littlefs
build_flags = 
    -Os
    -D USE_LITTLEFS
    -D USE_AUDIO
    -D USE_AI
    -D BOARD_HAS_PSRAM
    -Iinclude
    -DLV_CONF_INCLUDE="lv_conf.h"
    -Ilib/Fonts
    -D CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN=16384
    -D CONFIG_ESP_MAIN_TASK_STACK_SIZE=8192
    -D CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=32768
    -D CONFIG_ESP_TASK_WDT_TIMEOUT_S=60
    -D LV_FONT_MONTSERRAT_10=1
    # -D USE_WS_ASR             # 启用 WebSocket 流式 ASR；取消注释以启用
lib_deps = 
    ${common.lib_deps_base}
    lvgl/lvgl@^8.3.9
    bodmer/TFT_eSPI@2.5.0
    bitbank2/JPEGDEC @ ^1.6.2
build_src_filter = ${common.filter_base} +<ai/> +<tftv/>
